"""add cars, pricing, rentals, state_history, payments, workshop_visits, processed_events

Revision ID: eddf6d24e70f
Revises: 3f4abfadee7d
Create Date: 2026-09-19 22:48:25.597488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eddf6d24e70f'
down_revision: Union[str, Sequence[str], None] = '3f4abfadee7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('car_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_WORKSHOP', name='carstatus'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_car_class'), 'cars', ['car_class'], unique=False)
    op.create_index(op.f('ix_cars_plate_no'), 'cars', ['plate_no'], unique=True)
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lateness_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_car_class'), 'pricing', ['car_class'], unique=True)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=True)
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('RESERVED', 'ACTIVE', 'RETURNED', 'CANCELLED', name='rentalstate'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rentals_car_daterange', 'rentals', ['car_id', 'start_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_rentals_car_id'), 'rentals', ['car_id'], unique=False)
    op.create_index(op.f('ix_rentals_customer_id'), 'rentals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rentals_state'), 'rentals', ['state'], unique=False)
    op.create_table('workshop_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_visits_car_id'), 'workshop_visits', ['car_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('DEPOSIT', 'FINAL', name='paymentkind'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_rental_id'), 'payments', ['rental_id'], unique=False)
    op.create_table('state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('RESERVED', 'ACTIVE', 'RETURNED', 'CANCELLED', name='rentalstate'), nullable=False),
    sa.Column('to_state', sa.Enum('RESERVED', 'ACTIVE', 'RETURNED', 'CANCELLED', name='rentalstate'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_history_rental_id'), 'state_history', ['rental_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_history_rental_id'), table_name='state_history')
    op.drop_table('state_history')
    op.drop_index(op.f('ix_payments_rental_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_workshop_visits_car_id'), table_name='workshop_visits')
    op.drop_table('workshop_visits')
    op.drop_index(op.f('ix_rentals_state'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_customer_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_car_id'), table_name='rentals')
    op.drop_index('ix_rentals_car_daterange', table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_pricing_car_class'), table_name='pricing')
    op.drop_table('pricing')
    op.drop_index(op.f('ix_cars_plate_no'), table_name='cars')
    op.drop_index(op.f('ix_cars_car_class'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
